#!/usr/bin/env python3

def throw_exception():
    names = ['Alice', 'Bob', 'Charlie']

    for i in range(4):
        print(names[i])

if __name__ == '__main__':
    throw_exception()
